# -*- coding: utf-8 -*-
"""l2.z2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lU_g9Ic0OzqS_9IOMS6zZSEJu7LsTN3c
"""

from PIL import Image
import os
def min(sciezkapliku, sciezka_min):
  rozm=160,90
  file, ext = os.path.splitext(sciezkapliku)
  with Image.open(sciezkapliku) as im:
    im.thumbnail(rozm)
    im.save(sciezka_min)
  
#min("IMG_20210625_124943.jpg" + "miniatura","jpg")

from PIL import Image
import glob, os

size = 128, 128

for infile in glob.glob("*.jpg"):
    file, ext = os.path.splitext(infile)
    with Image.open(infile) as im:
        im.thumbnail(size)
        im.save(file + ".thumbnail", "JPEG")

"""https://pillow.readthedocs.io/en/latest/handbook/index.html
https://pillow.readthedocs.io/en/stable/PIL.html
https://pillow.readthedocs.io/en/stable/
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.transform
"""