# -*- coding: utf-8 -*-
"""l2.z6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nji-lxW2YTfCaWKvM5XhqS11lqPLS0P9
"""

#a=input("wpisz zadanie matematyczne używając + i - lub *")
a="437+127-125+9"
wynik=eval(a)
print(wynik)
if "*" in a:
  if "+" in a or "-" in a:
    print("wynik to : ",wynik, " rozwiązanie jest zbyt skomplikowane, żeby je pokazywać")
  else:
    a=a.split('*')
    print(" "*(10-len(a[0])),a[0])
    print("*"," "*(8-len(a[-1])),a[-1])
    print("-"*11)
    for i in range(len(a[1])):
      b=str(int(a[0])*int(a[1][i-1]))
      if i<len(a[1])-1:
        print(" "*(10-i-len(b)),b)
      else: 
        print("+"," "*(8-i-len(b)),b)
    print("-"*11)
    print(" "*(10-len(str(wynik))),wynik)
else:
  a=str(a).split("+")
  a=str(a).split("-") # trzeba potem dodać tego minusa 
  for i in range(0,len(a)-1):
    print(" "*(10-len(a[i])),a[i])
  
    
    
     


#print(a)

#b=a.split('+')
#for i in range(0,len(b)):
#  if "-" in b[i]:
#    b[i]=b[i].split('-')
#    print(b,"jest -")
#print(b)

#print(b[1])

